### ISSUE TITLE
Can not connecting to Zealot

### ISSUE THREAD

**Issue by rkonfj** [getzealot/fastlane-plugin-zealot#10]
之前的一段时间内，zealot插件都工作的非常棒，但就在昨天上传包时出现了这个错误
```
[19:30:52]: Uploading to https://myzealotdomain ...
[19:46:42]: Can not connecting to Zealot
```

可能时当时的`zealot`服务器不可用。所以，插件有什么机制可以处理这种异常吗？

**Comment by icyleaf** [comment]
通常这样的情况属于 zealot 服务宕机或者反代服务出现了异常无法正常访问造成的。

fastlane 不支持多语言因此统一采用的是英文的表述方式，后续我再想想如何更让普通用户理解的方式

**Comment by rkonfj** [comment]
> 通常这样的情况属于 zealot 服务宕机或者反代服务出现了异常无法正常访问造成的。
> 
> fastlane 不支持多语言因此统一采用的是英文的表述方式，后续我再想想如何更让普通用户理解的方式

针对服务器临时停机，上传这块可不可以有一个重试机制，这样在`zealot`服务器短暂不可用后，依然能正确上传

**Comment by icyleaf** [comment]
插件已经有内置重试机制，重试 3 次，每次间隔 5 秒

https://github.com/tryzealot/fastlane-plugin-zealot/blob/8a34cea/lib/fastlane/plugin/zealot/helper/zealot_helper.rb#L166

服务宕机属于物理故障，软件侧怎么保全都没法 100% 避免。

**Comment by rkonfj** [comment]
> 插件已经有内置重试机制，重试 3 次，每次间隔 5 秒
> 
> https://github.com/tryzealot/fastlane-plugin-zealot/blob/8a34cea/lib/fastlane/plugin/zealot/helper/zealot_helper.rb#L166
> 
> 服务宕机属于物理故障，软件侧怎么保全都没法 100% 避免。

OK.
