### ISSUE TITLE
打包时报错

### ISSUE THREAD

**Issue by huangyake** [getzealot/fastlane-plugin-zealot#7]
错误提示: Can not connecting to Zealot

请问这个问题怎么解决, 或者说我怎么查看详细的错误日志呢

**Comment by icyleaf** [comment]
没有任何有效信息

**Comment by huangyake** [comment]
具体报错请看下面的文件
(https://user-images.githubusercontent.com/14834303/170427816-805289cb-49cc-4ebf-afd8-df7f953c08d5.jpg)
